Add support for non-pipe webcam recordings (RecordRTC, AWS S3)
lookit/lookit-api pull request #1237
Opened 2023-06-28 21:33 UTC by becky-gilbert

Relates to issue: #1074 (but merging this PR shouldn't automatically close the issue)

This PR contains some of the changes required to support our pipe-replacement webcam recordings:
- Adds AWS S3 environment variables (to be passed into the EFP build, and used when accessing videos for lookit-api views like researcher downloads and participant study history)
- Adds new 'recording_method' field  (value: 'pipe' or 'recordrtc') to Response model
- Adds new video API view that allows AWS S3 to send information about new video uploads, which is then used to create new Video objects in the database
- Adds video API tests

2023-07-10 17:13 UTC, okaycj requested changes
Just one question for now.

2023-07-10 17:16 UTC, becky-gilbert commented on studies/models.py
> +        return self.response.recording_method
Got it, thanks!

2023-07-19 21:25 UTC, becky-gilbert commented on studies/models.py
> +
@okaycj how's this?

2023-07-19 21:29 UTC, becky-gilbert commented on studies/models.py
> +        return self.response.recording_method
I've updated this by turning this into two methods that return booleans: `recording_method_is_pipe` and `recording_method_is_recordrtc`. I flagged the change for you with [this comment](https://github.com/lookit/lookit-api/pull/1237/files#diff-990438d44609ae4095e9e633d1447b4858ec59867eaa939f30b4e3cf9cebd684R1405-R1412). Please let me know if you have feedback!

2023-07-26 17:42 UTC, okaycj commented on studies/models.py
> +
Nice.

2023-07-26 17:43 UTC, okaycj approved these changes
I can't wait to test this in develop.  Nice work.

2023-08-10 22:44 UTC, merged